//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Project_Client_Powers.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/WCF_Project_Library_Powers")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int[] ScoresField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string First {
            get {
                return this.FirstField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstField, value) != true)) {
                    this.FirstField = value;
                    this.RaisePropertyChanged("First");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Last {
            get {
                return this.LastField;
            }
            set {
                if ((object.ReferenceEquals(this.LastField, value) != true)) {
                    this.LastField = value;
                    this.RaisePropertyChanged("Last");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int[] Scores {
            get {
                return this.ScoresField;
            }
            set {
                if ((object.ReferenceEquals(this.ScoresField, value) != true)) {
                    this.ScoresField = value;
                    this.RaisePropertyChanged("Scores");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IStudentService")]
    public interface IStudentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetStudentByID", ReplyAction="http://tempuri.org/IStudentService/GetStudentByIDResponse")]
        WCF_Project_Client_Powers.ServiceReference1.Student GetStudentByID(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetStudentByID", ReplyAction="http://tempuri.org/IStudentService/GetStudentByIDResponse")]
        System.Threading.Tasks.Task<WCF_Project_Client_Powers.ServiceReference1.Student> GetStudentByIDAsync(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/AddNewStudent", ReplyAction="http://tempuri.org/IStudentService/AddNewStudentResponse")]
        bool AddNewStudent(string firstName, string lastName, int ID, int[] scores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/AddNewStudent", ReplyAction="http://tempuri.org/IStudentService/AddNewStudentResponse")]
        System.Threading.Tasks.Task<bool> AddNewStudentAsync(string firstName, string lastName, int ID, int[] scores);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/AddGrade", ReplyAction="http://tempuri.org/IStudentService/AddGradeResponse")]
        bool AddGrade(int grade, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/AddGrade", ReplyAction="http://tempuri.org/IStudentService/AddGradeResponse")]
        System.Threading.Tasks.Task<bool> AddGradeAsync(int grade, int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/BelowAverage", ReplyAction="http://tempuri.org/IStudentService/BelowAverageResponse")]
        WCF_Project_Client_Powers.ServiceReference1.Student[] BelowAverage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/BelowAverage", ReplyAction="http://tempuri.org/IStudentService/BelowAverageResponse")]
        System.Threading.Tasks.Task<WCF_Project_Client_Powers.ServiceReference1.Student[]> BelowAverageAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStudentServiceChannel : WCF_Project_Client_Powers.ServiceReference1.IStudentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentServiceClient : System.ServiceModel.ClientBase<WCF_Project_Client_Powers.ServiceReference1.IStudentService>, WCF_Project_Client_Powers.ServiceReference1.IStudentService {
        
        public StudentServiceClient() {
        }
        
        public StudentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public WCF_Project_Client_Powers.ServiceReference1.Student GetStudentByID(int ID) {
            return base.Channel.GetStudentByID(ID);
        }
        
        public System.Threading.Tasks.Task<WCF_Project_Client_Powers.ServiceReference1.Student> GetStudentByIDAsync(int ID) {
            return base.Channel.GetStudentByIDAsync(ID);
        }
        
        public bool AddNewStudent(string firstName, string lastName, int ID, int[] scores) {
            return base.Channel.AddNewStudent(firstName, lastName, ID, scores);
        }
        
        public System.Threading.Tasks.Task<bool> AddNewStudentAsync(string firstName, string lastName, int ID, int[] scores) {
            return base.Channel.AddNewStudentAsync(firstName, lastName, ID, scores);
        }
        
        public bool AddGrade(int grade, int ID) {
            return base.Channel.AddGrade(grade, ID);
        }
        
        public System.Threading.Tasks.Task<bool> AddGradeAsync(int grade, int ID) {
            return base.Channel.AddGradeAsync(grade, ID);
        }
        
        public WCF_Project_Client_Powers.ServiceReference1.Student[] BelowAverage() {
            return base.Channel.BelowAverage();
        }
        
        public System.Threading.Tasks.Task<WCF_Project_Client_Powers.ServiceReference1.Student[]> BelowAverageAsync() {
            return base.Channel.BelowAverageAsync();
        }
    }
}
